services:
  postgres:
      build: ./postgres
      ports:
        - "5433:5432"
      volumes:
        - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
        - ./postgres/data:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: postgres
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready --username=admin --dbname=postgres" ]
        interval: 10s
        timeout: 5s
        retries: 5
      restart: always
  mqtt-client:
    build: ./mqtt-client
    ports:
      - "1883:1883"
    env_file:
      - .env
    develop:
      watch:
        - action: sync+restart
          path: ./mqtt-client
          target: /mqtt-client
    restart: unless-stopped